version: '3.8'
volumes:
  kdv-ldap:
services:
  frontend:
    container_name: KdV-Frontend
    build:
      context: frontend
      args:
        - VITE_API_URL=http://localhost:8081
    ports:
      - "80:8080"
    restart: on-failure
  backend:
    depends_on: [ldap]
    container_name: KdV-Backend
    build:
      context: backend
    ports:
      - "8081:8081"
    volumes:
      - ./kdv-data:/data
    restart: on-failure
  ldap:
    container_name: KdV-LDAP
    image: bitnami/openldap:latest
    ports:
      - 389:1389
    volumes:
      - kdv-ldap:/bitnami/openldap
      - ./ldif:/ldif
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: adminpassword
      LDAP_ROOT: dc=fsinfo,dc=fim,dc=uni-passau,dc=de
      LDAP_ADMIN_DN: cn=admin,dc=fsinfo,dc=fim,dc=uni-passau,dc=de
      LDAP_CUSTOM_LDIF_DIR: /ldif
