version: '3.8'
volumes:
  kdv-ldap:
networks:
  kdv:
services:
  frontend:
    container_name: KdV-Frontend
    build:
      context: frontend
      args:
        - VITE_API_URL=http://localhost:8081
    ports:
      - "8080:8080"
    restart: on-failure
  backend:
    depends_on: [ ldap ]
    container_name: KdV-Backend
    build:
      context: backend
      args:
        - LDAP_URI=ldap://ldap:1389/dc=fsinfo,dc=fim,dc=uni-passau,dc=de
    ports:
      - "8081:8081"
    networks:
      - kdv
    volumes:
      - ./.data:/data
    restart: on-failure
  ldap:
    container_name: KdV-LDAP
    image: bitnami/openldap:latest
    ports:
      - "1389:1389"
    networks:
      - kdv
    volumes:
      - kdv-ldap:/bitnami/openldap
      - ./ldif:/ldif
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: adminpassword
      LDAP_ROOT: dc=fsinfo,dc=fim,dc=uni-passau,dc=de
      LDAP_ADMIN_DN: cn=admin,dc=fsinfo,dc=fim,dc=uni-passau,dc=de
      LDAP_CUSTOM_LDIF_DIR: /ldif
