version: '3.8'
services:
  frontend:
    container_name: KdV-Frontend
    build:
      context: frontend
      args:
        - VITE_API_URL=http://localhost:8081
    ports:
      - "80:8080"
    restart: on-failure
  backend:
    container_name: KdV-Backend
    build: backend
    ports:
      - "8081:8081"
    volumes:
      - ./kdv-data:/data
    restart: on-failure