version: '3.8'
services:
  frontend:
    build:
      context: frontend
      args:
        - VITE_API_URL=http://localhost:8081
    container_name: crawly-frontend
    ports:
      - "80:8080"
    restart: on-failure
  backend:
    build: backend
    ports:
      - "8081:8081"
    volumes:
      - ./kdv:/tmp/kdv
    restart: on-failure