spring:
  datasource:
    url: jdbc:h2:file:/tmp/kdv/kdv
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: false # enable in debug
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop # "update" | "create-drop" for dev
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
server:
  port: 8081
  error:
    include-stacktrace: never
kdv:
  save-location: /tmp/kdv