spring:
  datasource:
    url: jdbc:mariadb://${DB_URL:mariadb:3306}/PRoST_SQL
    driverClassName: org.mariadb.jdbc.Driver
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:password}
  jpa:
    show-sql: false # enable in debug
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update # "update" | "create-drop" for dev
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
server:
  port: ${PORT:8081}
  error:
    include-stacktrace: never
logging:
  level:
    org:
      springframework:
        security: ${LOGGING_LEVEL:INFO}
        web: ${LOGGING_LEVEL:INFO}
        data: ${LOGGING_LEVEL:INFO}
prost:
  save-location: ${DATA_LOCATION:prost-data}
  ldap-uri: ${LDAP_URI:ldap://ldap:1389/dc=fsinfo,dc=fim,dc=uni-passau,dc=de}