spring:
  datasource:
    url: jdbc:h2:file:/tmp/kdv
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: false # enable in debug
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8081
  error:
    include-stacktrace: never