spring:
  datasource:
    url: jdbc:h2:file:${DATA_LOCATION:./prost-data}/prost
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: false # enable in debug
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop # "update" | "create-drop" for dev
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
server:
  port: 8081
  error:
    include-stacktrace: never
prost:
  save-location: ${DATA_LOCATION:prost-data}
  ldap-uri: ${LDAP_URI:ldap://ldap:1389/dc=fsinfo,dc=fim,dc=uni-passau,dc=de}